### PR TITLE
Add example flask app

### PR DESCRIPTION
**Pull request by hobbsh**
I spent a lot of time reading through the code in order to figure out how to structure my messages so tasks would pick them up. Hopefully this example Flask app and readme will make it easier for people to get up and running with PyQS. There's also a chance overall implementation is simpler so it would be great to clarify that in this PR. Also, this addresses #39. 

Let me know what you think!

### CODE REVIEW

**Comment by spulec** [comment]
Thanks for your work on this!

I think I am missing something though. Is there a reason to encourage this vs calling the syntax:  `send_email.delay(subject='Hi there')`?

**Comment by hobbsh** [comment]
@spulec not sure I follow you. Within the confines of this example, do you mean I could just do `process.delay(message={"some": "message"})` instead of constructing the message like I am?

**Comment by spulec** [comment]
Yes, that should work

**Comment by hobbsh** [comment]
@spulec Updated, thanks for pointing that out.

**Comment by spulec** [comment]
Looks great, thanks!

**Pull request merged**
